// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kFNDsJP3Pv1ltrWrMYh5Ie-dWnFMn6Q',
    appId: '1:953407757856:web:d00be9ab8b2c70f1dea645',
    messagingSenderId: '953407757856',
    projectId: 'senra-805d0',
    authDomain: 'senra-805d0.firebaseapp.com',
    storageBucket: 'senra-805d0.firebasestorage.app',
    measurementId: 'G-1ZEEZT2SQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrGXzBWIiJUxMf8oNqxXze2vLSUHQFLao',
    appId: '1:953407757856:android:82587565b27ff378dea645',
    messagingSenderId: '953407757856',
    projectId: 'senra-805d0',
    storageBucket: 'senra-805d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDek0NibLWoGi_CsJLbB9UL68CyK1pyGBU',
    appId: '1:953407757856:ios:0408d679ac7478ffdea645',
    messagingSenderId: '953407757856',
    projectId: 'senra-805d0',
    storageBucket: 'senra-805d0.firebasestorage.app',
    iosBundleId: 'com.example.senraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDek0NibLWoGi_CsJLbB9UL68CyK1pyGBU',
    appId: '1:953407757856:ios:0408d679ac7478ffdea645',
    messagingSenderId: '953407757856',
    projectId: 'senra-805d0',
    storageBucket: 'senra-805d0.firebasestorage.app',
    iosBundleId: 'com.example.senraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kFNDsJP3Pv1ltrWrMYh5Ie-dWnFMn6Q',
    appId: '1:953407757856:web:e5e52946da3a832bdea645',
    messagingSenderId: '953407757856',
    projectId: 'senra-805d0',
    authDomain: 'senra-805d0.firebaseapp.com',
    storageBucket: 'senra-805d0.firebasestorage.app',
    measurementId: 'G-86ZYPRJJHH',
  );
}
